EduKiteService/Controllers/GradeController.cs
using EdukiteService.Business.Interface;
using EdukiteService.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace EduKiteService.Controllers
{
    public class GradeController : ApiController
    {
        private readonly IGradeService _GradeService;

        public GradeController(IGradeService GradeService)
        {
            _GradeService = GradeService;
        }
        [HttpGet]
        [Route("api/grade/GetGrades")]
        public HttpResponseMessage GetAllGrades()
        {

            var Grades = _GradeService.GetGrades();

            return Request.CreateResponse(HttpStatusCode.OK, new APIMessage { StatusCode = (int)HttpStatusCode.OK, StatusMessage = Constants.SuccessMessage, Data = Grades });

        }
    }
}

EduKiteService/Controllers/GradesController.cs
using AutoMapper;
using EdukiteService.Business.Entities;
using EdukiteService.Business.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EduKiteService.Controllers
{
    public class GradesController : Controller
    {
        private readonly IGradeService _GradeService;
        private readonly ISubjectService _subjectService;
        private readonly IModuleService _ModuleService;

        public GradesController(IGradeService gradeService, ISubjectService subjectService, IModuleService moduleService)
        {
            try
            {
                _GradeService = gradeService;
                _subjectService = subjectService;
                _ModuleService = moduleService;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult GetGrades()
        {
            ViewData["vdOnlyGradeRoot"] = true;
            List<GradeModel> gradeModels2 = _GradeService.GetGrades();
            return View(gradeModels2);
        }


        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                ViewData["vdOnlyGradeRoot"] = true;
                List<GradeModel> gradeModel = _GradeService.GetGrades().ToList();
                ViewBag.GradeData = gradeModel;

            }
            catch (Exception ex)
            {
                throw ex;
                //return View();
            }
            return View();
            }

        [HttpPost]
        public ActionResult Create(GradeModel gradeData)
        {
            try
            {
                if (gradeData.GradeName != null)
                {
                    var addGrade = new GradeModel();
                    addGrade.GradeName = gradeData.GradeName;
                    addGrade.Description = gradeData.Description;
                    _GradeService.AddGrades(addGrade);
                    ViewBag.GradeData = _GradeService.GetGrades().ToList();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("GetGrades", "Grades");

        }


        public ActionResult Edit(int id)
        {
            try
            {
                ViewData["vdOnlyGradeRoot"] = true;
                var getGrade = _GradeService.GetGradeById(id);
                var gradeDispay = new GradeModel();
                gradeDispay.GradeId = getGrade.GradeId;
                gradeDispay.GradeName = getGrade.GradeName;
                gradeDispay.Description = getGrade.Description;
                ViewBag.GradeData = _GradeService.GetGrades().ToList();
                return View(gradeDispay);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }

        [HttpPost]
        public ActionResult Edit(GradeModel gradeData)
        {
            try
            {
                _GradeService.UpdateGrade(gradeData);
                ViewBag.GradeData = _GradeService.GetGrades().ToList();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("GetGrades", "Grades");

        }

        public JsonResult IsGradeNameExist(string GradeName, string initialGradeName)
        {
            try
            {
                if (GradeName == initialGradeName)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                var data = _GradeService.GetGradeByName(GradeName);

                if (data != null)
                {
                    return Json("Grade name already exists", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }


        public ActionResult PublishGrade(int id)
        {
            try
            {
                _GradeService.PublishGrade(id);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("GetGrades", "Grades");

        }

        public ActionResult DeleteGrade(int id)
        {
            try
            {
               _ModuleService.DeleteModule(id);
                
                _subjectService.DeleteSubjectAll(id);
                _GradeService.DeleteGrade(id);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("GetGrades", "Grades");

        }



        public void GetPublishedGrade(int GradeId)
        {
            bool GradePublishFlag = _GradeService.IsGradePublished(GradeId);

            TempData["GradePublishFlag"] = GradePublishFlag;
            TempData.Keep();
        }
    }
}

EduKiteService/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EdukiteService.Business.Entities;
using EdukiteService.Business.Interface;
using EdukiteService.Data;
using System.IO;
using System.IO.Compression;
using System.Threading.Tasks;

namespace EduKiteService.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ISubjectService _subjectService;
        private readonly IIconsService _iconsService;
        private readonly IGradeService _gradeService;
        private readonly IModuleService _ModuleService;
        private readonly ITopicService _TopicService;
        public SubjectsController(ISubjectService subjectService, IIconsService iconsService, IGradeService gradeService, IModuleService moduleService,ITopicService topicService)
        {
            _subjectService = subjectService;
            _iconsService = iconsService;
            _gradeService = gradeService;
            _ModuleService = moduleService;
            _TopicService = topicService;
        }


        // GET: Subjects
        [HttpGet]
        public ActionResult GetSubjects(int id)
        {
            EdukiteService.Business.Entities.CommonSubjectIconModel model = new EdukiteService.Business.Entities.CommonSubjectIconModel();
            model.SubjectVM = new SubjectModel();
            model.IconsVM = new IconsModel();
            ViewBag.GradeID = id;

            List<SubjectModel> subjectModel = _subjectService.GetSubjects(id); // need to pass gradeID
            ViewData["vdOnlyGradeName"] = _gradeService.GetGradeNameByGradeID(id);
            //ViewBag.GradeName = _gradeService.GetGradeNameByGradeID(id);
            return View(subjectModel);
        }

        // GET: Subjects/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Subjects/Create
        [HttpGet]
        public ActionResult Create(int id)
        {
            ViewBag.GradeName = _gradeService.GetGradeNameByGradeID(id);
            TempData.Remove("SubjectName");
            TempData["GradeID"] = id;
            TempData.Keep();
            ViewData["ThemeData"] = _subjectService.GetThemes();
            ViewBag.GradeID = id;
            List<SubjectModel> subjectModel = _subjectService.GetSubjects(id);
            ViewBag.SubjectData = subjectModel;
            ViewData["vdOnlyGradeName"] = _gradeService.GetGradeNameByGradeID(id);
            return View();
        }


        // POST: Subjects/Create
        [HttpPost]
        public ActionResult Create(CommonSubjectIconModel data)
        {
            int GradeID = 0;
            int subId = 0;
            try
            {
                List<Icon> iData = new List<Icon>();
                string strDDLValue = string.Empty;
                // GradeID = Convert.ToInt32(TempData["GradeID"]);
                GradeID = Convert.ToInt32(Request.Form["gradeId"]);
                ViewData["ThemeData"] = _subjectService.GetThemes();
                HttpPostedFileBase file = data.IconsVM.PostedFile;
                if (Request.Form["SelectedTheme"] != null && Request.Form["SelectedTheme"] != "")
                {
                    strDDLValue = Request.Form["SelectedTheme"].ToString();
                    if (file != null)
                    {
                        
                        data.SubjectVM.Themedb = strDDLValue;
                        data.SubjectVM.GradeID = GradeID;
                        data.SubjectVM.Code = GradeID + data.SubjectVM.ShortForm;//RikArena 
                        
                        subId = _subjectService.AddSubject(data.SubjectVM);
                        iData = GetFileData(file, GradeID, subId);
                        _iconsService.AddIcon(iData, subId);
                        // return RedirectToAction("GetSubjects", "subjects", new { @id = GradeID });
                    }
                }

               string gradeName = _gradeService.GetGradeNameByGradeID(GradeID);
                ModuleModel moduleModel = new ModuleModel();
                moduleModel.ModuleName = gradeName + " " + data.SubjectVM.SubjectName;
                    moduleModel.CreatedDatime = DateTime.Now;
                    moduleModel.GradeId = GradeID;
                    moduleModel.SubjectId = subId;
               string str = _ModuleService.AddModule(moduleModel);
              }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("GetSubjects", "subjects", new { @id = GradeID });
        }


        private List<Icon> GetFileData(HttpPostedFileBase file, int gradeId, int subId)
        {
            List<Icon> iData = new List<Icon>();
            try
            {
                if (file.ContentLength > 0)
                {
                    var gradePath = Path.Combine(Server.MapPath("~/Content/Upload"), gradeId.ToString());
                    var subPath = Path.Combine(Server.MapPath("~/Content/Upload/" + gradeId.ToString()), subId.ToString());
                    if (!(Directory.Exists(gradePath)) && !(Directory.Exists(subPath)))
                    {
                        Directory.CreateDirectory(gradePath);
                        Directory.CreateDirectory(subPath);
                        iData = GetFileInfo(file, gradeId, subId);
                    }
                    else if ((Directory.Exists(gradePath)) && !(Directory.Exists(subPath)))
                    {
                        Directory.CreateDirectory(subPath);
                        iData = GetFileInfo(file, gradeId, subId);
                    }
                    else
                    {
                        foreach (string fn in Directory.GetFiles(subPath))
                        {
                            System.IO.File.Delete(fn);
                        }
                        iData = GetFileInfo(file, gradeId, subId);
                    }                    
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return iData;
        }

        private List<Icon> GetFileInfo(HttpPostedFileBase file, int gradeId, int subId)
        {
            List<Icon> iData = new List<Icon>();
            try
            {

                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Upload/" + gradeId.ToString() + "/" + subId.ToString()), fileName);
                file.SaveAs(path);
                string zipPath = path;
                using (ZipArchive archive = ZipFile.OpenRead(zipPath))
                {
                    foreach (ZipArchiveEntry entry in archive.Entries)
                    {
                        if (entry != null)
                        {
                            Icon im = new Icon();
                            string[] values = entry.Name.Split('.');
                            im.IconName = entry.Name;
                            im.IconPath = entry.FullName;
                            im.IconType = values[1].ToString();
                            iData.Add(im);
                        }
                                             

                    }

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return iData;

        }


        // GET: Subjects/Edit/5
        [HttpGet]
        public ActionResult Edit(int id, int GradeID)
        {
            ViewData["vdOnlyGradeName"] = _gradeService.GetGradeNameByGradeID(GradeID);
            TempData.Remove("GradeID");
            ViewBag.GradeName = _gradeService.GetGradeNameByGradeID(GradeID);
            EdukiteService.Business.Entities.CommonSubjectIconModel model = new EdukiteService.Business.Entities.CommonSubjectIconModel();
            model.SubjectVM = new SubjectModel();
            model.IconsVM = new IconsModel();
            try
            {
                List<SubjectModel> subjectModel = _subjectService.GetSubjects(GradeID);
                ViewBag.SubjectData = subjectModel;
                ViewBag.GradeID = GradeID;

                ViewData["ThemeData"] = _subjectService.GetThemes();
                var subData = _subjectService.GetSubjectById(id);
                model.SubjectVM.SubjectId = subData.SubjectId;
                model.SubjectVM.SubjectName = subData.SubjectName;
                TempData["SubjectName"] = model.SubjectVM.SubjectName;
                TempData["GradeID"] = GradeID;
                TempData.Keep();
                model.SubjectVM.Themedb = subData.Themedb;
                model.SubjectVM.ShortForm = subData.ShortForm;
                model.SubjectVM.Description = subData.Description;
                model.SubjectVM.GradeID = subData.GradeID;
                string iconName = _iconsService.GetIconById(id);
                model.IconsVM.IconName = iconName.Split('/')[0].ToString() + ".zip";

                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return View(model);
        }

        // POST: Subjects/Edit/5
        [HttpPost]
        public ActionResult Edit(CommonSubjectIconModel data)
        {
            try
            {
                List<Icon> iData = new List<Icon>();
                string strDDLValue = string.Empty;
                if (Request.Form["SelectedTheme"] != null && Request.Form["SelectedTheme"] != "")
                {
                    strDDLValue = Request.Form["SelectedTheme"].ToString();
                    data.SubjectVM.Themedb = strDDLValue;
                    _subjectService.UpdateSubject(data.SubjectVM);
                    HttpPostedFileBase file = data.IconsVM.PostedFile;
                    if (file != null)
                    {

EduKiteService/Views/Grades/Create.cshtml
@model EdukiteService.Business.Entities.GradeModel


@{
    ViewBag.Title = "Create";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <!-- Main content -->
            <section class="content backend-middle-main-container">

                <div class="backend-middle-main-container-inner">
                    <div class="col-lg-7 col-sm-6 col-md-6 col-xs-12">
                        @if (ViewBag.GradeData != null)
                        {
                            @Html.Partial("_GetAllGrades", (IEnumerable<EdukiteService.Business.Entities.GradeModel>)ViewBag.GradeData)
                        }
                    </div>

                    <div class="col-lg-5 col-sm-6 col-md-6 col-xs-12">
                        <div class="form-container">
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Add Grade</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" action="/Grades/Create" id="createForm" method="post">

                                    @using (Html.BeginForm())
                                    {

                                        @Html.AntiForgeryToken()


                                        <div class="box-body">



                                            <div class="form-group">

                                                <label for="exampleInputEmail1" class="control-label col-md-2">Name*</label>
                                                <div>
                                                    @Html.EditorFor(model => model.GradeName, new { htmlAttributes = new { @type = "number", @class = "form-control height-75" } })
                                                    @Html.ValidationMessageFor(model => model.GradeName, "", new { @class = "text-danger" })

                                                </div>
                                            </div>



                                            <div class="form-group">
                                                <label for="exampleInputPassword1" class="control-label col-md-2">Description</label>
                                                <div>
                                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control height-75" } })
                                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <p class="help-block">*The grade will have to be published manually using the <a href="#" class="publish-btn">&nbsp;</a> icon.</p>
                                            </div>

                                        </div>
                                    <!-- /.box-body -->

                                        <div class="box-footer">
                                            <div class="box-footer-inner col-lg-8 col-sm-10 col-md-8 col-xs-12">

                                                <input type="submit" value="Create" class="btn btn-default" />

                                                @*<button type="submit" class="btn btn-grey pull-right">Cancel</button>*@
                                                <input type="button" Value="Cancel" class="btn btn-grey pull-right" id="cancelGrade" onclick="location.href='@Url.Action("GetGrades", "Grades")'">
                                            </div>
                                        </div>
                                    }

                                </form>
                            </div>
                        </div>
                        <!--<img src="img/div-place-right.png" class="" alt="backend" style="height: auto; width: 76%;">-->
                    </div>
                </div>

            </section>

        </div>
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validate")
}

EduKiteService/Views/Grades/Edit.cshtml
@model EdukiteService.Business.Entities.GradeModel

@{
    ViewBag.Title = "Edit";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <!-- Main content -->
            <section class="content backend-middle-main-container">

                <div class="backend-middle-main-container-inner">
                    <div class="col-lg-7 col-sm-6 col-md-6 col-xs-12">
                       
                        @if (ViewBag.GradeData != null)
                        {
                            @Html.Partial("_GetAllGrades", (IEnumerable<EdukiteService.Business.Entities.GradeModel>)ViewBag.GradeData)
                        }
                    </div>

                    <div class="col-lg-5 col-sm-6 col-md-6 col-xs-12">
                        <div class="form-container">
                            <div class="box box-primary">
                                <div class="box-header">
                                    <a href="#" class="delete-btn">&nbsp;</a>
                                    <h3 class="box-title">Edit Grade</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" action="/Grades/Edit" id="editForm" method="post">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Hidden("initialGradeName", Model.GradeName)
                                    <div class="box-body">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <div class="form-group" style="display:none">
                                            @Html.LabelFor(model => model.GradeId, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div>
                                                @Html.EditorFor(model => model.GradeId, new { htmlAttributes = new { @class = "form-control height-75" } })
                                                @Html.ValidationMessageFor(model => model.GradeId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                                                             

                                        <div class="form-group">
                                            <label for="exampleInputName" class="control-label col-md-2">Name*</label>
                                            <div >
                                                @Html.EditorFor(model => model.GradeName, new { htmlAttributes = new { @class = "form-control height-75" } })
                                                @Html.ValidationMessageFor(model => model.GradeName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                          <label for="exampleInputDesc" class="control-label col-md-2">Description</label>
                                            <div >
                                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control height-75" } })
                                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <p class="help-block">*The grade will have to be published manually after any changes made.</p>
                                        </div>

                                    </div>

                                    <!-- /.box-body -->

                                    <div class="box-footer">
                                        <div class="box-footer-inner col-lg-8 col-sm-10 col-md-8 col-xs-12">
                                            <input type="submit" value="Save" class="btn btn-default" />
                                            <input type="button" Value="Cancel" class="btn btn-grey pull-right" id="cancelGrade" onclick="location.href='@Url.Action("GetGrades", "Grades")'">
                                        </div>
                                    </div>
}

                                </form>
                            </div>
                        </div>
                        <!--<img src="img/div-place-right.png" class="" alt="backend" style="height: auto; width: 76%;">-->
                    </div>
                </div>

            </section>

        </div>
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="mi-modal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                @*<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>*@
                <h4 class="modal-title" style="color:black" id="myModalLabel">Are you sure, You want to Delete?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modal-btn-yes">Yes</button>
                <button type="button" class="btn btn-primary" id="modal-btn-no">No</button>
            </div>
        </div>
    </div>
</div>






@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
      var modalConfirm = function (callback) {

        $(".delete-btn").on("click", function () {
            $("#mi-modal").modal('show');
        });

        $("#modal-btn-yes").on("click", function () {
            callback(true);
            $("#mi-modal").modal('hide');
        });

        $("#modal-btn-no").on("click", function () {
            callback(false);
            $("#mi-modal").modal('hide');
        });
    };

    modalConfirm(function (confirm) {
        if (confirm) {
            window.location.href = '@Url.Action("DeleteGrade", "Grades")' + '?id=' + @Model.GradeId;

            } else {
            //Acciones si el usuario no confirma
            // $("#result").html("NO CONFIRMADO");
            }
            });

            </script>
}

EduKiteService/Views/Grades/GetGrades.cshtml
@model IEnumerable<EdukiteService.Business.Entities.GradeModel>

@{
    ViewBag.Title = "GetGrades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <!-- Main content -->
            <section class="content backend-middle-main-container">

                <div class="backend-middle-main-container-inner">
                    <div class="col-lg-7 col-sm-6 col-md-6 col-xs-12 verticle-separate horizontal-separate">
                        @Html.Partial("_GetAllGrades", Model)
                    </div>

                    <div class="col-lg-5 col-sm-6 col-md-6 col-xs-12">
                        <div class="form-container">
                            <div class="box box-primary">
                                <!-- form start -->
                                <form role="form" class="no-border">
                                    <div class="box-body">
                                        @*<button type="submit" class="btn btn-grey btn-centered uppercase padd-left-right-35">Add <br>Grade</button>*@

                                        <input type="button" Value="Add Grade" class="btn btn-grey btn-centered uppercase padd-left-right-35" id="addGrade" onclick="location.href='@Url.Action("Create", "Grades")'">
                                    </div>
                                    <!-- /.box-body -->
                                </form>
                            </div>
                        </div>
                        <!--<img src="img/div-place-right.png" class="" alt="backend" style="height: auto; width: 76%;">-->
                    </div>
                </div>

            </section>

        </div>
    </div>
    <!-- /.content -->
</div>

EduKiteService/Views/Grades/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

EduKiteService/Views/Grades/_GetAllGrades.cshtml
@model IEnumerable<EdukiteService.Business.Entities.GradeModel>

@foreach (var item in Model)
{
    <div class="col-lg-3 col-md-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-light-grey">
            @if (!item.IsPublished)
            {
                <a href="@Url.Action("PublishGrade", "Grades", new { id = item.GradeId })" class="edit-asset publish-btn">&nbsp;</a>
            }
            else if (item.IsPublished )
            {
                Html.RenderAction("GetPublishedSubjectCount", "Subjects", new { GradeId = item.GradeId});
                if (Convert.ToBoolean(TempData["SubPublishFlag"])) {
                <a href = "@Url.Action("PublishGrade", "Grades", new { id = item.GradeId })" class="edit-asset republish-btn">&nbsp;</a>
                }
            }
            <div class="inner">

                <h3>Grade</h3>
                <a href="@Url.Action( "getsubjects","subjects", new { id = item.GradeId })">
                    <p>@Html.DisplayFor(modelItem => item.GradeName)</p>
                </a>
            </div>
            <a href="@Url.Action("Edit", "Grades", new { id = item.GradeId })" class="edit-asset edit-btn"></a>
        </div>
    </div>
}   