EduKiteService/Controllers/AssetController.cs
using EdukiteService.Business.Entities;
using EdukiteService.Business.Interface;
using EdukiteService.Data;
using EdukiteService.Data.interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace EduKiteService.Controllers
{
    public class AssetController : Controller
    {
        private readonly IAssetService _assetService;
        private readonly ISubTopicService _subtopicservice;
        private readonly ITopicService _topicService;
        private readonly ISubjectService _subjectService;
        private readonly IGradeService _gradeService;
        public AssetController(IAssetService assetService, ISubTopicService subTopicService, ITopicService topicService, ISubjectService subjectService, IGradeService gradeService)
        {
            _assetService = assetService;
            _subtopicservice = subTopicService;
            _topicService = topicService;
            _subjectService = subjectService;
            _gradeService = gradeService;
        }



        // GET: Asset
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public int CreateData(FormCollection assetData)
        {
            AssetModel adata = new AssetModel();
            try
            {
                adata.AssetId = Guid.Parse(assetData["AssetId"]);
                adata.isAssetHide = true;
                adata.AssetName = assetData["AssetName"];
                adata.AssetTypeId = Convert.ToInt32(assetData["AssetTypeId"]);
                if (assetData["SubtopicId"] != null && assetData["SubtopicId"] != "")
                    adata.SubtopicId = Convert.ToInt32(assetData["SubtopicId"]);
                adata.Description = assetData["Description"];
                adata.TopicId = Convert.ToInt32(assetData["TpoicId"]);
                adata.isAssetHide = true;
                TempData["AssetData"] = adata;
                TempData.Keep();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Convert.ToInt32(assetData["AssetTypeId"]);
             }

        [HttpGet]
        public ActionResult CreateSimulationorInteractive(int id)
        {
            AssetModel ad = new AssetModel();
            try
            {
                TempData["TopicId"] = id;
                TempData.Keep();
                int topicID = Convert.ToInt32(TempData["TopicId"]);
                getSTAData(topicID);
                List<AssetTypeModel> assetTypeSimIntData = _assetService.GetSimIntAssetType();
                ViewData["assetTypeSimIntData"] = assetTypeSimIntData;
                ad = (AssetModel)TempData["AssetData"];
                AddHeaderForMore(topicID, Convert.ToInt32(ad.SubtopicId));
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(ad);
        }

        private void getSTAData(int topicID)
        {
            try
            {
                CommonSubTopicAssetModel model = new CommonSubTopicAssetModel();
                List<SubTopicModel> subTopicData = _subtopicservice.GetSubTopics(topicID); // need to pass topic id
                ViewData["SubTopicData"] = subTopicData;
                model.SubTopicVM = subTopicData;
                model.AssetVM = _assetService.GetAssetByTopicId(topicID);
                ViewBag.SubTopicAssetData = model;
                List<AssetTypeModel> assetTypeData = _assetService.GetAssetType();
                ViewData["AssetTypeData"] = assetTypeData;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult CreateSimulationorInteractive(AssetModel assetData)
        {
            string gradeName;
            string subjectName;

            int TopicId = 0;
            try
            {
                TopicId = Convert.ToInt32(assetData.TopicId);
                Tuple<string, string> res = getSubtopicandAssetTypeData(TopicId);
                gradeName = res.Item1;
                subjectName = res.Item2;
                var data = new AssetModel();
                data.AssetId = assetData.AssetId;
                data.SuggestedActiveDuration = assetData.SuggestedActiveDuration;
                data.AssetName = assetData.AssetName;
                data.Description = assetData.Description;

                if (TempData["isAssetHide"] != null)
                {
                    data.isAssetHide = Convert.ToBoolean(TempData["isAssetHide"]);
                }
                else
                {
                    data.isAssetHide = true;
                }

                if (Request.Form["SelectedMoreScreenSubTopic"] != null && Request.Form["SelectedMoreScreenSubTopic"] != "")
                {
                    data.SubtopicId = Convert.ToInt32(Request.Form["SelectedMoreScreenSubTopic"]);
                }
                else
                {
                    data.SubtopicId = null;
                }

                if (Request.Form["SelectedSimIntAssetType"] != null && Request.Form["SelectedSimIntAssetType"] != "")
                {
                    data.AssetTypeId = Convert.ToInt32(Request.Form["SelectedSimIntAssetType"]);
                }
                else
                {
                    data.AssetTypeId = Convert.ToInt32(assetData.AssetTypeId);
                }

                if (assetData.PostedFileZip != null)
                {
                    uploadFile(assetData.PostedFileZip, assetData.AssetId.ToString(), gradeName, subjectName, data.AssetTypeId);
                    data.FileName = TempData["FileName"].ToString();
                    data.ThumbnailFileName = TempData["ImageName"].ToString();
                    data.FolderName = TempData["FolderName"].ToString();
                }
                data.TopicId = TopicId;
                string assetId = _assetService.AddAssetInsert(data);

                // }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("GetSubTopics", "SubTopics", new { @id = TopicId });

        }

        private Tuple<string, string> getSubtopicandAssetTypeData(int topicId)
        {
            int TopicId = topicId;
            var res = (Tuple<string, string>)null;
            try
            {
                res = getSubjectNameandGradeName(TopicId);
                List<SubTopicModel> subTopicData = _subtopicservice.GetSubTopics(TopicId); // need to pass topic id
                ViewData["SubTopicData"] = subTopicData;
                List<AssetTypeModel> assetTypeData = _assetService.GetAssetType();
                ViewData["AssetTypeData"] = assetTypeData;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return res;

        }

        private Tuple<string, string> getSubjectNameandGradeName(int topicId)
        {
            int gradeId;
            int subjectId;
            int TopicId = topicId;
            var res = (Tuple<string, string>)null;
            try
            {
                TopicModel tdata = _topicService.GetTopicById(TopicId);
                subjectId = tdata.SubjectId;
                SubjectModel sdata = _subjectService.GetSubjectById(subjectId);
                gradeId = Convert.ToInt32(sdata.GradeID);
                var modelSubject = _subjectService.GetSubjectById(subjectId);
                string GradeName = _gradeService.GetGradeNameByGradeID(gradeId);
                res = Tuple.Create<string, string>(GradeName, modelSubject.SubjectName);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return res;
        }


        //private void UploadZipFileWithoutSubtopic(Guid AssetId, int GradeId, int SubjectId, int TopicId, int? SubTopicId, int oldSubtopicId)
        //{
        //    try
        //    {

        //        var gradePath = Path.Combine(Server.MapPath("~/Content/Upload"), GradeId.ToString());
        //        var subPath = Path.Combine(Server.MapPath("~/Content/Upload/" + GradeId.ToString()), SubjectId.ToString());
        //        var topicPath = Path.Combine(Server.MapPath("~/Content/Upload/" + GradeId.ToString() + "/" + SubjectId.ToString()), TopicId.ToString());
        //        var subTopicPath = string.Empty;
        //        var pathAsset = string.Empty;
        //        var oldPathAsset = string.Empty;
        //        subTopicPath = Path.Combine(Server.MapPath("~/Content/Upload/" + GradeId.ToString() + "/" + SubjectId.ToString() + "/" + TopicId.ToString()), SubTopicId.ToString());
        //        pathAsset = Path.Combine(Server.MapPath("~/Content/Upload/" + GradeId.ToString() + "/" + SubjectId.ToString() + "/" + TopicId.ToString() + "/" + SubTopicId.ToString()), AssetId.ToString());
        //        if (oldSubtopicId != 0)
        //        {

        //            oldPathAsset = Path.Combine(Server.MapPath("~/Content/Upload/" + GradeId.ToString() + "/" + SubjectId.ToString() + "/" + TopicId.ToString() + "/" + oldSubtopicId.ToString()), AssetId.ToString());
        //        }
        //        else
        //        {

        //            oldPathAsset = Path.Combine(Server.MapPath("~/Content/Upload/" + GradeId.ToString() + "/" + SubjectId.ToString() + "/" + TopicId.ToString()), AssetId.ToString());
        //        }               

        //        if (!(Directory.Exists(gradePath)) && !(Directory.Exists(subPath)) && !(Directory.Exists(topicPath)) && !(Directory.Exists(subTopicPath)) && !(Directory.Exists(pathAsset)))
        //        {
        //            Directory.CreateDirectory(gradePath);
        //            Directory.CreateDirectory(subPath);

EduKiteService/Controllers/SubTopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EduKiteService.Controllers
{
    public class SubTopicController : Controller
    {
        // GET: SubTopic
        public ActionResult Index()
        {
            return View();
        }

        // GET: SubTopic/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SubTopic/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SubTopic/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SubTopic/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SubTopic/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SubTopic/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SubTopic/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EduKiteService/Views/SubTopics/GetSubTopics.cshtml
@using EdukiteService.Business.Entities;
@model EdukiteService.Business.Entities.CommonSubTopicAssetModel

@{
    ViewBag.Title = "GetSubTopics";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <!-- Main content -->
            <section class="content backend-middle-main-container">

                <div class="backend-middle-main-container-inner">
                    <div class="col-lg-8 col-sm-6 col-md-6 col-xs-12">
                     
                        @*@Html.Partial("_GetSubTopics", Model)*@
                        @Html.Partial("~/Views/SubTopics/_GetSubTopics.cshtml", Model)
                    </div>

                    <div class="col-lg-4 col-sm-6 col-md-6 col-xs-12">
                        <div class="form-container topic-form-container">
                            <div class="box box-primary">
                                <!-- form start -->
                                <form role="form" class="no-border">
                                    <div class="box-body">
                                        <button type="button" onclick="location.href='@Url.Action("Create", "SubTopics",new { id = ViewBag.TopicId })'" class="btn btn-grey btn-centered uppercase padd-left-right-8">Add <br>SubTopic</button>
                                    </div>

                                    <div class="box-body">
                                        <button type="button" onclick="location.href='@Url.Action("Create", "Asset",new { id = ViewBag.TopicId })'" class="btn btn-grey btn-centered uppercase padd-left-right-35">Add <br>Asset</button>

                                    </div>
                                    <!-- /.box-body -->
                                </form>
                            </div>
                        </div>
                        <!--<img src="img/div-place-right.png" class="" alt="backend" style="height: auto; width: 76%;">-->
                    </div>
                </div>

            </section>

        </div>
    </div>
    <!-- /.content -->
  
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/bootstrap")

    <script>

        $(function () {
            $(".list-group-sortable").sortable({

                update: function (event, ui) {

                    var orderSb = 1;
                    var orderA = 1;
                    var modelSB = [];
                    var modelAssetWithoutSubtopic = [];
                    var orderAssetWithoutSubtopic = 1;
                    debugger;
                    var modelA = [];
                    $("ul#sbSortable>li").each(function () {
                        $('ul#sbSortable').sortable('disable');
                        var hdn = $('#hdnSB', '.list-group-sortable li').eq(orderSb - 1);
                        var objModel = { SubtopicId: hdn.val(), SubtopicNo: orderSb };
                        modelSB.push(objModel);
                        orderSb++;
                    });

                    $("ul#assetSortable>li").each(function () {
                        $('ul#assetSortable').sortable('disable');
                        var hdn = $('#hdnAsset', '.list-group-sortable li').eq(orderA - 1);
                        var objModel = { AssetId: hdn.val(), AssetNo: orderA };
                        modelA.push(objModel);
                        orderA++;
                    });


                    $("ul#ulAssetWithoutSubtopicSort>li").each(function () {
                        $('ul#ulAssetWithoutSubtopicSort').sortable('disable');
                        var hdn = $('#hdnAssetWithoutSubtopic', '.list-group-sortable li').eq(orderAssetWithoutSubtopic - 1);
                        var objModel = { AssetId: hdn.val(), AssetNo: orderAssetWithoutSubtopic };
                        modelAssetWithoutSubtopic.push(objModel);
                        orderAssetWithoutSubtopic++;
                    });

                    if (modelAssetWithoutSubtopic.length > 1) {
                        $.ajax({
                            type: "POST",
                            contentType: "application/json; charset=utf-8",
                            url: '@Url.Action("UpdateAssetOrderAsync", "SubTopics")',
                            data: JSON.stringify({ lstAssetModel: modelAssetWithoutSubtopic }),
                            success: function (data) {
                                location.reload();
                            },
                            error: function (jqXHR, exception) {
                                var msg = '';
                                if (jqXHR.status === 0) {
                                    msg = 'Not connect.\n Verify Network.';
                                } else if (jqXHR.status == 404) {
                                    msg = 'Requested page not found. [404]';
                                } else if (jqXHR.status == 500) {
                                    msg = 'Internal Server Error [500].';
                                } else if (exception === 'parsererror') {
                                    msg = 'Requested JSON parse failed.';
                                } else if (exception === 'timeout') {
                                    msg = 'Time out error.';
                                } else if (exception === 'abort') {
                                    msg = 'Ajax request aborted.';
                                } else {
                                    msg = 'Uncaught Error.\n' + jqXHR.responseText;
                                }
                                alert(msg);

                            }
                        });
                    }

                    if (modelSB.length > 1) {
                        $.ajax({
                            type: "POST",
                            contentType: "application/json; charset=utf-8",
                            url: '@Url.Action("UpdateSubTopicsOrderAsync", "SubTopics")',
                            data: JSON.stringify({ lstSubTopicModel: modelSB }),
                            success: function (data) {
                                location.reload();
                            },
                            error: function (jqXHR, exception) {
                                var msg = '';
                                if (jqXHR.status === 0) {
                                    msg = 'Not connect.\n Verify Network.';
                                } else if (jqXHR.status == 404) {
                                    msg = 'Requested page not found. [404]';
                                } else if (jqXHR.status == 500) {
                                    msg = 'Internal Server Error [500].';
                                } else if (exception === 'parsererror') {
                                    msg = 'Requested JSON parse failed.';
                                } else if (exception === 'timeout') {
                                    msg = 'Time out error.';
                                } else if (exception === 'abort') {
                                    msg = 'Ajax request aborted.';
                                } else {
                                    msg = 'Uncaught Error.\n' + jqXHR.responseText;
                                }
                                alert(msg);

                            }
                        });
                    }

                    if (modelA.length > 1) {
                        $.ajax({
                            type: "POST",
                            contentType: "application/json; charset=utf-8",
                            url: '@Url.Action("UpdateAssetOrderAsync", "SubTopics")',
                            data: JSON.stringify({ lstAssetModel: modelA }),
                            success: function (data) {
                                location.reload();
                            },
                            error: function (jqXHR, exception) {
                                var msg = '';
                                if (jqXHR.status === 0) {
                                    msg = 'Not connect.\n Verify Network.';
                                } else if (jqXHR.status == 404) {
                                    msg = 'Requested page not found. [404]';
                                } else if (jqXHR.status == 500) {
                                    msg = 'Internal Server Error [500].';
                                } else if (exception === 'parsererror') {
                                    msg = 'Requested JSON parse failed.';
                                } else if (exception === 'timeout') {
                                    msg = 'Time out error.';
                                } else if (exception === 'abort') {
                                    msg = 'Ajax request aborted.';
                                } else {
                                    msg = 'Uncaught Error.\n' + jqXHR.responseText;
                                }
                                alert(msg);

                            }
                        });
                    }
                }

            });



        });


    </script>
}
@Styles.Render("~/Content/css") 

EduKiteService/Views/SubTopics/_GetSubTopics.cshtml
@using EdukiteService.Business.Entities;
@model EdukiteService.Business.Entities.CommonSubTopicAssetModel


<div class="topic-list-conainer">
    <ul>
        <li>
            @if (ViewBag.AssetsWithoutSubTopic != null)
            {
                @Html.Partial("~/Views/Asset/_GetAssets.cshtml", (IEnumerable<EdukiteService.Business.Entities.AssetModel>)ViewBag.AssetsWithoutSubTopic)
            }
        </li>
        <li>
            <ul id="sbSortable" class="list-group list-group-sortable">
                @foreach (var item1 in Model.SubTopicVM)
                 {

                    <li id="sbLi" class="list-group-item">

                        <span class="topic-number pull-left">
                            @Html.DisplayFor(modelItem => item1.SubtopicNo)
                        </span>
                        <div class="topic-list-inner col-lg-11">
                            <input type="hidden" id="hdnSB" value="@item1.SubtopicId" />
                            @Html.DisplayFor(modelItem => item1.SubtopicName)
                            <span class="topic-edit pull-right edit-asset edit-btn"><a href="@Url.Action("Edit", "SubTopics", new { id = item1.SubtopicId })">&nbsp;</a></span>
                        </div>




                        <ul id="assetSortable" class="list-group sub-topic-list list-group-sortable">


                            @foreach (var item2 in Model.AssetVM)
                            {
                                if (item1.SubtopicId == item2.SubtopicId)
                                {
                            <li class="list-group-item topic-margin-left">
                                @*<span class="pull-left">@Html.DisplayFor(modelItem => item2.AssetNo)</span>*@
                                @if (item2.isAssetHide && item2.AssetTypeId == 1)
                                        {
                                <a href=""><span class="sub-topic-left video-green pull-left">&nbsp;</span></a>
                                        }
                                        else if(!item2.isAssetHide && item2.AssetTypeId == 1)
                                        {
                                <a href=""><span class="sub-topic-left video-red pull-left">&nbsp;</span></a>
                                        }

                                @if (item2.isAssetHide && (item2.AssetTypeId == 3 || item2.AssetTypeId == 4))
                                {
                                    <a href=""><span class="sub-topic-left int-green pull-left">&nbsp;</span></a>
                                }
                                else if (!item2.isAssetHide && (item2.AssetTypeId == 3 || item2.AssetTypeId == 4))
                                {
                                    <a href=""><span class="sub-topic-left int-red pull-left">&nbsp;</span></a>
                                }

                                <div class="sub-topic-list-inner col-lg-11">
                                    <input type="hidden" id="hdnAsset" value="@item2.AssetId" />
                                    @Html.DisplayFor(modelItem => item2.AssetName)
                                    <span class="topic-edit pull-right edit-asset edit-btn">
                                        <a href="@Url.Action("Edit", "Asset", new { id = item2.AssetId, topicID = item2.TopicId })">&nbsp;</a>

                                    </span>
                                </div>
                            </li>
                                }


                            }
                        </ul>




                    </li>
                }
            </ul>
        </li>
    </ul>
</div>